### ISSUE TITLE
screen mode doesn't update screen at designated times

### ISSUE THREAD

**Issue by paletochen** [Phambili-Tech/Newt_RV_3028_C7#61]
I have screen mode activated for a couple of days and i can confirm that it doesn't update the mode nor at night nor in the morning.
Is it just me or a bug?

If the former, how can i fix it?

Thanks

**Comment by darianbjohnson** [comment]
It's a known bug - https://github.com/Phambili-Tech/Newt_Display/issues/43 - hoping to get it fixed by the next release

**Comment by paletochen** [comment]
Oh, sorry, I missed that bug. Then closing this issue
